Repository allanoguis/coding-notes, pull requests merged in 2024-10, with the labels that each got.

#7 Added remaining notes for ReactJS and updated readme
  README.md
  ReactJS/deployment.md
  ReactJS/forms.md
  ReactJS/routing.md
  ReactJS/stateManagement.md
  ReactJS/styling.md
  ReactJS/testing.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#8 properly linked the readme to navigate to respective files
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#12 Feature/nodejs notes added
  NodeJS/architecture.md
  NodeJS/async_programming.md
  NodeJS/best_practices.md
  NodeJS/core_modules.md
  NodeJS/deployment.md
  NodeJS/error_handling.md
  NodeJS/features.md
  NodeJS/introduction.md
  NodeJS/npm.md
  NodeJS/restful_apis.md
  NodeJS/setup.md
  NodeJS/testing.md
  NodeJS/web_server.md
  README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#13 Added AngularJS notes
  AngularJS/Angular CLI.md
  AngularJS/Angular Documentation.md
  AngularJS/Angular Universal for SSR.md
  AngularJS/Components And Templates.md
  AngularJS/Data Binding and Directives.md
  AngularJS/Deployment.md
  AngularJS/Forms.md
  AngularJS/Getting Started.md
  AngularJS/HTTP Client.md
  AngularJS/Introduction.md
  AngularJS/Performance Optimizations.md
  AngularJS/Pipes.md
  AngularJS/Routing and Navigation.md
  AngularJS/Services and Dependency Injection.md
  AngularJS/State Management.md
  AngularJS/Testing.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#14 Update README.md
  README.md
Labels: good first issue
